security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\UsersAuthenticator
      logout:
        path: app_logout
        # Redirection après déconnexion
        # target: app_home

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800 # 7 jours
        path: /
        # always_remember_me: true # décommenter pour toujours activer cette option

  # Contrôle d'accès pour certaines parties du site en fonction des rôles
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      # Utiliser des valeurs faibles pour les tests afin de réduire le temps nécessaire au hachage
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # valeur minimale pour bcrypt
        time_cost: 3 # valeur minimale pour argon
        memory_cost: 10 # valeur minimale pour argon
